{"name": "после оформления заказа его номер появляется в разделе В работе", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <test_order.TestCreateOrder object at 0x04918E50>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"4ad6f3ae-c08b-4752-8596-ce65a21da0d9\")>\nsetup_and_teardown = None\n\n>   ???\n\nC:\\Users\\moov\\yandex\\Diplom\\Diplom_тут\\tests\\test_order.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\main_page.py:52: in add_filling_to_order\n    self.wait_clickable(MainPageLocators.BUN_INGREDIENT)\npages\\base_page.py:28: in wait_clickable\n    WebDriverWait(self.driver, 3).until(ec.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"4ad6f3ae-c08b-4752-8596-ce65a21da0d9\")>\nmethod = <selenium.webdriver.support.expected_conditions.element_to_be_clickable object at 0x0144A710>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nvenv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "steps": [{"name": "Авторизация", "status": "passed", "steps": [{"name": "Перейти на страницу авторизации по кнопке \"Войти в аккаунт\"", "status": "passed", "start": 1740264426099, "stop": 1740264426418}, {"name": "Заполняем поле \"email\"", "status": "passed", "parameters": [{"name": "user_email", "value": "'michael60@example.com'"}], "start": 1740264426419, "stop": 1740264426545}, {"name": "Заполняем поле \"Пароль\"", "status": "passed", "parameters": [{"name": "user_password", "value": "'_tLcnbBr9CQR'"}], "start": 1740264426545, "stop": 1740264426591}, {"name": "Нажимаем кнопку «Войти»", "status": "passed", "start": 1740264426591, "stop": 1740264426881}], "parameters": [{"name": "user_login", "value": "'michael60@example.com'"}, {"name": "user_password", "value": "'_tLcnbBr9CQR'"}], "start": 1740264426099, "stop": 1740264426881}, {"name": "Добавить ингридиент в заказ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\moov\\yandex\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\moov\\yandex\\Diplom\\Diplom_3\\pages\\main_page.py\", line 52, in add_filling_to_order\n    self.wait_clickable(MainPageLocators.BUN_INGREDIENT)\n  File \"C:\\Users\\moov\\yandex\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\moov\\yandex\\Diplom\\Diplom_3\\pages\\base_page.py\", line 28, in wait_clickable\n    WebDriverWait(self.driver, 3).until(ec.element_to_be_clickable(locator))\n  File \"C:\\Users\\moov\\yandex\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Ждем элемент", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\moov\\yandex\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\moov\\yandex\\Diplom\\Diplom_3\\pages\\base_page.py\", line 28, in wait_clickable\n    WebDriverWait(self.driver, 3).until(ec.element_to_be_clickable(locator))\n  File \"C:\\Users\\moov\\yandex\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', '//p[text()=\"Флюоресцентная булка R2-D3\"]')"}], "start": 1740264426881, "stop": 1740264429964}], "start": 1740264426881, "stop": 1740264429966}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1740264425357, "stop": 1740264429968, "uuid": "49e7d140-fc05-4798-88f5-976fdfbe9fd2", "historyId": "403f19171f52fbefcc1737bf07b85c26", "testCaseId": "2d926418fb8ce5647fd3180f79479164", "fullName": "tests.test_order.TestCreateOrder#test_new_order_appears_in_work_list", "labels": [{"name": "suite", "value": "Лента заказов"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "LAPTOP-JTVFLPC5"}, {"name": "thread", "value": "14800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}